server:
  port: 8085
  servlet:
    context-path: /monitoring

  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:monitoring
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true

  # configuration for client and server
  security:
    user:
      name: user
      password: password

  # configuration for client
  boot:
    admin:
      client:
        url: http://localhost:8085/monitoring
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        # configuration for client (data sent to the server to connect to client)
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        # configuration for server
        routes:
          endpoints: ${management.endpoints.web.exposure.include}

flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}
  schemas: PUBLIC
  location: classpath:db/migration
  validate-on-migrate: true

# configuration for client
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - flyway
          - env
          - metrics
          - beans
          - mappings
          - prometheus
