server:
  port: 8085
  servlet:
    context-path: /monitoring

  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:monitoring
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true

  security:
    user:
      name: user
      password: password

flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}
  schemas: PUBLIC
  location: classpath:db/migration
  validate-on-migrate: true

management:
  endpoints:
      web:
        exposure:
          include:
          - health
          - info
          - flyway
          - env
          - metrics
          - beans
          - mappings
          - prometheus
