server:
  port: 9001
  servlet:
    context-path: /oauth

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # TODO Add your client id
            client-secret: # TODO Add your client secret
            scope: # TODO Required scopes
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs