server:
  port: 8082
  servlet:
    context-path: /security-basic

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:security-basic;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver

  flyway:
    enabled: false

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG