server:
  port: 8082
  servlet:
    context-path: /security-basic

spring:
  datasource:
    url: jdbc:h2:mem:error-handling
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

  security:
    user:
      name: admin
      password: password

debug: true